fix = true
indent-width = 4
line-length = 88
required-version = ">=0.11.10"
show-fixes = true

[lint]
ignore = [
  "D203", # conflicts with the preferred D211
  "D213", # conflicts with the preferred D212
]
select = ["ALL"]

[lint.per-file-ignores]
"scripts/*" = ["INP001"]

[format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = false
