# builds mkdocs, reusable by other checks

name: Build Docs Pages
description: Build Docs Pages for mkdocs workflows.

runs:
  using: composite
  steps:
    - uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # 3.3.0
      with:
        environment-file: build_env.yml
        activate-environment: mkdocs
        miniforge-version: latest

    - name: Build Pages # this is both a build and check step
      run: mkdocs build --strict
      shell: bash -l {0} # must have -l because conda requires login shell to function in subsequent steps
