# builds mkdocs, reusable by other checks

name: Build Docs Pages
description: Build Docs Pages for mkdocs workflows.

runs:
  using: composite
  steps:
    - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # 4.0.1
      with:
        environment-file: env_build.yml
        activate-environment: mkdocs-build
        miniforge-version: 26.3.2-3
        run-init: false
        remove-profiles: false

    - name: Build Pages # this is both a build and check step
      shell: bash
      run: |
        source "$CONDA/etc/profile.d/conda.sh"
        conda activate mkdocs-build
        mkdocs build --strict
