name: Bug Report
description: Let us know about bugs!
labels: ["fix: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking time to fill out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description:
        Please describe what happened. Screenshots and URLs of affected parts
        are welcome.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happen instead?
      description: Please describe what should have happened.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: devices
    attributes:
      label: What devices are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - Android
        - iOS
