# checks yaml for yaml-specific linting and formatting issues

name: yaml

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  check_yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2 # 3.0.0
        with:
          yamllint_config_filepath: ".yamllint.yaml"
          yamllint_strict: true
          yamllint_comment: true
