# checks python files for python linting and formatting issues

name: python

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  check_python:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        args: ["check", "format --check --diff"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # 4.1.0
        with:
          args: ${{ matrix.args }}
          version: 0.15.6
