# checks python files for python linting and formatting issues

name: python

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  check_python:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        args: ["check", "format --check --diff"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: astral-sh/ruff-action@eaf0ecdd668ceea36159ff9d91882c9795d89b49 # 3.4.0
        with:
          args: ${{ matrix.args }}
          version: 0.15.6
