# deploys documentation to gh-pages

name: docs

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch: # enables manual docs deployment in case of GitHub service issue

concurrency:
  group: "deploy-docs.rc.uab.edu-pages"
  cancel-in-progress: false

jobs:
  check_markdown:
    uses: "./.github/workflows/reusable_check_markdown.yml"
    with:
      globs: "docs/**/*.md"
  deploy_docs:
    needs: check_markdown
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # mkdocs-git-revision-date-localized-plugin
      - uses: "./.github/shared/build_docs_pages/"
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # 6.0.0
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # 5.0.0
        with:
          path: "./site"
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # 5.0.0
